
# This is a TOML formatted configuration file. 

# After it is parsed, fields that indicate filanames 
# (e.g end in 'FILE' or 'DIR' or 'PATH') will have 
# environment variables substituted. 

# $ROOT -- Environment variable set to project root
# $DATA -- Environment variable set to the data folder

[DISPLAY.PROGRESS]
DISABLE=false # Show progress bars for potentially slow operations.

# Logging configuration settings are passed directly to the logging
# library in python. Hence the odd case for the names. 
[LOGGING]
version=1
    [LOGGING.formatters.simple]
    format='%(asctime)s - %(levelname)s - %(message)s'

    [LOGGING.handlers.console]
    class = 'logging.StreamHandler'
    stream  = 'ext://sys.stdout'
    formatter = 'simple'

    [LOGGING.handlers.file]
    class = 'logging.handlers.RotatingFileHandler'
    filename = 'srp-boxes.log'
    formatter = 'simple'
    maxBytes = 4096
    backupCount = 3

    [LOGGING.root]
    level= 'DEBUG'
    handlers= ['console']

[COLOR]
FILE = '${DATA}/raw/srp/sec11-26949.tif'
CRS = 'epsg:26949'


[ANNOTATIONS]
FILE = '${DATA}/raw/srp/box-annotations.geojson'

[VOLUME]
FILE = '${DATA}/interim/srp/stack_a4b2/lidar_volume.vrt'
CRS = 'epsg:26949'

[VOLUME.Z]
MIN = -0.3048
MAX = 1.524
STEPS = 6

[TRAIN]
SRAND = 127
CLASS_BALANCE = [1, 1]
HARD_SAMPLING = false
PATCH_SIZE = 64 # Patch size  used for training

[TRAIN.SAMPLES]
DIR = '${DATA}/interim/samples'
FOLDS = 5
CURRENT_FOLD = 1

[TRAIN.SAMPLES.GENERATOR]
GSD = 0.0499  # Rescale inputs to that ground sample distance is ~ 2 inches
NUM_SAMPLES = 2000
PADDED_PATCH_SIZE = 96 # Size of a patch to generate _before_ cropping. 
NAME_PATTERN = '{label}/s{index:05}.pkl'  # the pattern to generate sample paths; label and index are the samples label and index....
MIN_SEPARATION = 2 # Two meters
DENSITY_LAYERS = [3,4]  # Which layers of the volume to threshold by MIN_DENSITY
MIN_DENSITY = 15  # Threshold on the volume-density; samples are only generated where density is greater than threshold.
BLOCK_SIZE = 4096 # Size of a block to page from huge files; should be as big as you can fit in RAM on your system

[TRAIN.AUGMENTATION]
VARIATIONS = 20
MAX_OFFSET = 15  # Unused? Units? (better be pixels -- should be meters)



